version: '2'
services:
    micromonitorsamplemicroservice-app:
        image: micromonitorsamplemicroservice
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${micromonitor.registry.password}@micromonitor-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${micromonitor.registry.password}@micromonitor-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://micromonitorsamplemicroservice-postgresql:5432/micromonitorSampleMicroservice
            - JHIPSTER_SLEEP=30 # gives time for the MicroMonitor Registry to boot before the application
    micromonitorsamplemicroservice-postgresql:
        extends:
            file: postgresql.yml
            service: micromonitorsamplemicroservice-postgresql
    micromonitor-registry:
        extends:
            file: micromonitor-registry.yml
            service: micromonitor-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
            - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/
