version: '2'
services:
    microclient-app:
        image: micromonitor-client
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${micromonitor.registry.password}@localhost:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${micromonitor.registry.password}@localhost:8761/config
            - MICROMONITOR_SLEEP=30 # gives time for the MicroMonitor Registry to boot before the application
    microclient:
        extends:
            file: micromonitor-client.yml
            service: micromonitor
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
            - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/
